### ISSUE TITLE
Image printing

### ISSUE THREAD

**Issue by smanaqvi83** [Klemen1337/node-thermal-printer#1]
Can you please provide help on printing of images in this printer? using the same API? 

Other printing is working fine, but we need to print images. Please help. 

Regards
Ali

**Comment by Klemen1337** [comment]
Hi Ali,
currently we are too busy to update the library. Here are some user manuals for star printers if that helps you. There is a good description how to print dot matrix graphics.
http://www.i-pos.nl/download/star/Prog%20manual%20TSP700.pdf
http://www.star-m.jp/eng/service/usermanual/linemode_cm_en.pdf

We hope to release a new version with image and qr printing in the next week or two.

Cheers,
Klemen

**Comment by smanaqvi83** [comment]
Hi,
Thanks. Waiting desperately for this update.

Regards
Ali

**Comment by zettam** [comment]
Any updates about this? Much appreciated!

**Comment by jmercha** [comment]
I have [fiddled around a little](https://github.com/jmercha/hue-ambience/blob/master/lib/color-mapper.js) with bitmaps in node before.

I also need image printing support for my projects as well, so I'd love to help out here! :smile

**Comment by Klemen1337** [comment]
@jmercha I see you made image.js to support image printing. Any luck?

**Comment by jmercha** [comment]
@Klemen1337 I got stuck trying to send the right escape codes to the printer and haven't looked at it since. I'll probably have another look next weekend.

**Comment by Klemen1337** [comment]
@jmercha, I just changed the library to work with buffer instead of strings. It should help with the problem you have.

More about buffer:
[https://nodejs.org/api/buffer.html](https://nodejs.org/api/buffer.html)

**Comment by sadlyblue** [comment]
Hi, I'm trying to insert an image for an Epson thermal printer, with no succes so far.
Can anyone help?
I looked at the epson references, but they are a little confusing to me.
Thanks

**Comment by Klemen1337** [comment]
@sadlyblue sorry this library dose not support image printing yet 😢

**Comment by sadlyblue** [comment]
I'm aware it doesn't support images yet. But could you help me configure it. If i'm able to to it, i'm happy to provide the code for integration in your library.
The main difficulty i have, after looking at the epson references is how should i calculate the pL and pH values (along with all the other values), in this function GS ( L pL pH m fn a bx by c xL xH yL yH d1...dk, and i guess i should pass the image as hex as well to the buffer.
After, i think i should use the https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=98 function 50 to print the image.
I'm trying to insert a fixed logo.

**Comment by pratikkulshreshth** [comment]
Any progress on this?

**Comment by dustinbolton** [comment]
Here's a library that can print images to a thermal printer BUT it is not an Epson or Star.  The command codes look different so I don't know if the image format itself is compatible but it may be helpful to someone who is further along in understanding the image formats this expects...

Library:
https://github.com/xseignard/thermalPrinter/blob/master/src/printer.js

Function:
 printImage() and printImageData() in this libr

**Comment by Klemen1337** [comment]
I just pushed an experimental :warning:  epson and star image printing, anyone knows why star printing doesnt work? If anyone can help that would be great :smile:

**Comment by Klemen1337** [comment]
UPDATE: @SloInfinity just pushed an update for EPSON image print. This library is now supporting PNG image printing for EPSON printers. He is still working on STAR support.

**Comment by Klemen1337** [comment]
Image printing done :smile:
