### ISSUE TITLE
messy code for chinese

### ISSUE THREAD

**Issue by jackyzonewen** [Klemen1337/node-thermal-printer#10]
when i want to print chinese, thr print result is messy code,how to solve this?thanks,i am new to nodejs.

**Comment by Klemen1337** [comment]
@jackyzonewen Im sorry I dont know how to help you with that. Try to change "characterSet"

**Comment by ronaldkan** [comment]
@jackyzonewen You could encode your text into 'GB18030' with the help of some libraries (for example, iconv-lite).

For example,
`
var printer = require("node-thermal-printer");
var iconv = require('iconv-lite');

printer.init({
  type: 'epson',
  interface: '/dev/usb/lp0'
});

printer.println(iconv.encode("华文字幕", 'GB18030'));
`
