### ISSUE TITLE
win10 Cannot print large image，it will be garbled

### ISSUE THREAD

**Issue by Anberm** [Klemen1337/node-thermal-printer#103]
I used win10 system to run examples/image.js on the 80mm thermal printer, and replaced olaii-logo-black-small-png with olaii-logo-black-png, which would print garbled code

**Comment by Klemen1337** [comment]
@Anberm what is the name of the thermal printer, what type of printer is it (eprson or star)?

**Comment by Anberm** [comment]
@Klemen1337 EPSON ,I printed it by slicing up the picture into small pictures, and it worked

**Comment by Klemen1337** [comment]
@Anberm Can you tell me how you did it?

**Comment by Anberm** [comment]
@Klemen1337 This is a problem of node-printer, so I will provide a reference solution：
 var dataBuffer = new Buffer(base64Data, 'base64');

  let PNG = require('pngjs').PNG;
  var png = PNG.sync.read(dataBuffer);
  var amp = 200;
  var dpi = parseInt(png.height / png.width);
  var pwidth = png.width + amp;
  var pheight = png.height + amp * dpi;
  var wh = 10;
  var len = pheight % wh ? Math.floor(pheight / wh) + 1 : pheight / wh;
  var remainder = pheight % wh;
  for (let x = 0; x < len; x++) {
    var height = x + 1 === len && remainder ? remainder : wh;
    var data = await sharp(dataBuffer)
      .resize(pwidth, pheight)
      .extract({
        left: 0,
        top: x * wh,
        width: pwidth,
        height: height,
      })
      .toBuffer();
    await printer.printImageBuffer(data);
  }
  printer.execute();

**Comment by peteruithoven** [comment]
For future reference, with syntax highlighting:
``` js 
var dataBuffer = new Buffer(base64Data, "base64");

let PNG = require("pngjs").PNG;
var png = PNG.sync.read(dataBuffer);
var amp = 200;
var dpi = parseInt(png.height / png.width);
var pwidth = png.width + amp;
var pheight = png.height + amp * dpi;
var wh = 10;
var len = pheight % wh ? Math.floor(pheight / wh) + 1 : pheight / wh;
var remainder = pheight % wh;
for (let x = 0; x < len; x++) {
  var height = x + 1 === len && remainder ? remainder : wh;
  var data = await sharp(dataBuffer)
    .resize(pwidth, pheight)
    .extract({
      left: 0,
      top: x * wh,
      width: pwidth,
      height: height,
    })
    .toBuffer();
  await printer.printImageBuffer(data);
}
printer.execute();
```
