### ISSUE TITLE
VIETNAMESE character set doesn't work

### ISSUE THREAD

**Issue by manhnguyenquoc** [Klemen1337/node-thermal-printer#110]
Hi @Klemen1337 , thank you for building this module. I'm from Vietnam and I'm trying to print Vietnamese words but I got the font error paper after printing.

For example: 
I would like to print "Công ty Cổ phần Viễn thông VNNET" and here is what I get:
![1231](https://user-images.githubusercontent.com/22399058/58786079-02242500-8611-11e9-8dd3-c97e8e25f863.jpg)

My code:
![12312](https://user-images.githubusercontent.com/22399058/58786096-081a0600-8611-11e9-803c-f44fc9e1de83.PNG)

Could you please tell me how to fix it. Thank you very much.

**Comment by MY020537** [comment]
@manhnguyenquoc Were you able to fix this ?

**Comment by manhtnt** [comment]
I got the same problem. Can anyone help us?
