### ISSUE TITLE
Type error on typescript

### ISSUE THREAD

**Issue by asnawisaharuddin** [Klemen1337/node-thermal-printer#113]
Unable to compile using typescript.

Error :
`node_modules/node-thermal-printer/node-thermal-printer.d.ts:18:14 - error TS2314: Generic type 'Promise<T>' requires 1 type argument(s).`

Probably need to specify return type of Promise<void | any>.

**Comment by hadeeb** [comment]
Type-definitions are out of sync with the changes in `v4`.

@Klemen1337 do you mind if I take up updating type-definitions?

**Comment by chunkitmax** [comment]
I have updated for typescript but I also renamed class printer and enum printerTypes.
Plase check [https://github.com/chunkitmax/node-thermal-printer](https://github.com/chunkitmax/node-thermal-printer)

**Comment by hadeeb** [comment]
@chunkitmax , I noticed you have multiple changes in your fork.
So, I created a [PR](https://github.com/Klemen1337/node-thermal-printer/pull/115) with type definition updates.
Will please you go through it?

**Comment by chunkitmax** [comment]
@hadeeb, I did not check those missing methods so your updates are more complete. I think your PR is good to be merged.

**Comment by Klemen1337** [comment]
I don't know how i missed this, but I worked on it today 😄
