### ISSUE TITLE
Support for Danish Character Set

### ISSUE THREAD

**Issue by nielsrobin** [Klemen1337/node-thermal-printer#119]
Hi, I've tried every Character Set on the list, but none of them seem to support Æ Ø Å (Danish), how do I add another character set and/or could UTF-8 be added somehow?

	printer.init({
		type: printer.printerTypes.STAR,
		interface: 'printer:' + printer_name,
		characterSet: '....'
	})

**Comment by Klemen1337** [comment]
Your printer might not support it. What brand and number is it?

**Comment by nielsrobin** [comment]
Star TSP143IIILAN
