### ISSUE TITLE
Cant Resolve Module : node-thermal-printer

### ISSUE THREAD

**Issue by MaheshEx1990** [Klemen1337/node-thermal-printer#120]
Installed plugin as shown but it not compiling
Throwing error Can't Find Module: node-thermal-printer

**Comment by Klemen1337** [comment]
Please provide more information.

**Comment by SimantoR** [comment]
I believe you need to build it on your own machine to be able to get that sorted. I might be wrong.

For me, this built the `node-printer` or in npmjs: `printer` module correctly. But node-printer has problems too such as not being able to find the `.node` module built from the native. I changed the `./lib/printer.js` as such on line 6:
`binding_path = './node_modules/printer/lib/node_printer.node'` which came to the problem of this module being compiled under `NODE_MODULE_VERSION 57` but mine is 75.

**Comment by Klemen1337** [comment]
@SimantoR so your problem was with the "printer" npm package and electron package rebuilding not "node-thermal-printer"?

**Comment by SimantoR** [comment]
Yes. Had to downgrade electron to 5.0.6 and build printer module using node-gyp to finally get it to work.

**Comment by Klemen1337** [comment]
@SimantoR Yeah rebuilding modules is a pain in the butt
