### ISSUE TITLE
setTextSize doesn't work in Epson LX-350

### ISSUE THREAD

**Issue by vadhack** [Klemen1337/node-thermal-printer#126]
In example: node-thermal-printer/examples/charsets.js

this is how print when call "printer.setTextSize(height, width)"

!wWow
!his is normal

add a some characters at start in buffer and the text size always is the same,

I used a printer: Epson LX-350

Can someone help me please?

**Comment by vadhack** [comment]
Can someone help me?

**Comment by Klemen1337** [comment]
@vadhack Not all printers have the same commands. Your printer might have a different set of commands.

Tested printers are:

- Star TSP700
- Rongta RP80US
- Rongta RP326-USE
- EPSON TM-T88V
- Posman BTP-R880NP (Type "epson")

**Comment by vadhack** [comment]
Thanks, do you know where can i get the correct commands?

**Comment by Klemen1337** [comment]
@vadhack I found them here [https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=2](https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=2)
