### ISSUE TITLE
Star BSC10 does not print Image correctly

### ISSUE THREAD

**Issue by CHOMNANP** [Klemen1337/node-thermal-printer#127]
I'm trying to print the image with printer model Star BSC10. As a result, the image did not print properly as image. The output is look like a random binary string.

![image](https://user-images.githubusercontent.com/5925050/69778696-dbb5ff80-11d7-11ea-8ed1-e3bd0346a919.png)

````
const ThermalPrinter = require("node-thermal-printer").printer;
const PrinterTypes = require("node-thermal-printer").types;

let printer = new ThermalPrinter({
    type: PrinterTypes.STAR,                                  // Printer type: 'star' or 'epson'
    interface: 'tcp://192.168.222.2',                       // Printer interface
    removeSpecialCharacters: false,                           // Removes special characters - default: false
    lineCharacter: "=",                                       // Set character for lines - default: "-"
    options: {                                                 // Additional options
        timeout: 5000                                           // Connection timeout (ms) [applicable only for network printers] - default: 3000
    }
});
await printer.printImage('./demo.png');  // Print PNG image
let execute = await printer.execute()

````

Look like an encoding issue. Anyone has similar experience?

**Comment by CHOMNANP** [comment]
Tried to reproduce this in PHP and found the same issue.
Here's how they fix it.
https://github.com/mike42/escpos-php/issues/222

**Comment by Klemen1337** [comment]
@CHOMNANP Not all printers have the same commands. Your printer might have a different print image command.

Tested printers are:
- Star TSP700
- Rongta RP80US
- Rongta RP326-USE
- EPSON TM-T88V
- Posman BTP-R880NP (Type "epson")
