### ISSUE TITLE
all node modules throwing error of "fs" in react-native 

### ISSUE THREAD

**Issue by mahesh-ahir** [Klemen1337/node-thermal-printer#129]
is there any way to use this lib for react-native cuz it's throwing error that Unable to resolve module `fs` from `node_modules/node-thermal-printer/lib/core.js`: fs could not be found within the project.and it's not only for fs all node modules are throwing error utils,buffer,zlib etc

**Comment by Oggy1986** [comment]
I was wondering same thing

> file.js:19 Uncaught (in promise) TypeError: fs.existsSync is not a function
    at File.isPrinterConnected (file.js:19)

**Comment by Klemen1337** [comment]
React native and NodeJs are completely different things.
