### ISSUE TITLE
Epson Picture Printing Garbled

### ISSUE THREAD

**Issue by buddy-lin** [Klemen1337/node-thermal-printer#130]
When the height of the picture is greater than or equal to 256 pixels, the picture will print garbled code. After testing, it has nothing to do with the amount of data.

**Comment by Klemen1337** [comment]
@buddy-lin What printer are you using?

**Comment by buddy-lin** [comment]
Thermal printer.However, pictures with a printing height less than 256 pixels can be printed normally

**Comment by buddy-lin** [comment]
Thermal printer.
However, pictures with a printing height less than 256 pixels can be printed normally.

**Comment by buddy-lin** [comment]
And the picture printing is in the middle. I want to use the command to change to left printing but it doesn't work

**Comment by buddy-lin** [comment]
> @ buddy-lin您正在使用什么打印机？

Is the problem solved?

**Comment by Klemen1337** [comment]
So just make image smaller than 256px?

**Comment by buddy-lin** [comment]
Yes，Print as long as the height is less than 256 pixels.
