### ISSUE TITLE
printer.setPrinterDriver(MyCustomDriver) example object

### ISSUE THREAD

**Issue by odegraciajr** [Klemen1337/node-thermal-printer#133]
May i know a sample driver object using `printer.setPrinterDriver(MyCustomDriver)`?

Im using xprinter thermal receipt printer

**Comment by selenecodes** [comment]
You can pass it a node-printer driver or fork as far as I know. For node <12 try `require('printer')` and for node > 12 try `require('@thiagoelg/node-printer')`

**Comment by selenecodes** [comment]
Also if you're using Electron with those you will need to rebuild.

For that you can use electron-rebuild using the following command
```
electron-rebuild -f -w @thiagoelg/node-printer
```

**Comment by jevy-wangfei** [comment]
> May i know a sample driver object using `printer.setPrinterDriver(MyCustomDriver)`?
> 
> Im using xprinter thermal receipt printer

Hi, Does your xprinter work with this node-thermal-printer package?  
I see xprinter Compatible to ESC/POS command.
