### ISSUE TITLE
Printer class gets a string but requires an object.

### ISSUE THREAD

**Issue by piratadelfuturo** [Klemen1337/node-thermal-printer#134]
Why this line gets a string but requires an object?

https://github.com/Klemen1337/node-thermal-printer/blob/a686a0d78effed4c321a1781af30af04755fbbef/lib/interfaces/index.js#L17

**Comment by antoniomgatto** [comment]
I  catched the same error here. I will send a pull request to fix this.

**Comment by antoniomgatto** [comment]
#135

**Comment by Klemen1337** [comment]
Fixed in v4.1.2
