### ISSUE TITLE
Expose module for partial cut

### ISSUE THREAD

**Issue by luckyagarwal3247** [Klemen1337/node-thermal-printer#14]
I see that the config file has partial cut config but is not exposed via any functions in the module. How can I use the partial cut feature?

**Comment by Klemen1337** [comment]
@dustinbolton added partial cut functionality! :smile:

**Comment by luckyagarwal3247** [comment]
I just uninstalled and reinstalled, didn't get the updated files. When would the latest files be available?

Thanks
Lucky

**Comment by Klemen1337** [comment]
It should be on now (v0.0.24)

**Comment by luckyagarwal3247** [comment]
Got it. Now I can keep my Kitchen Order Tickets from falling off and getting lost under tables. :)
Thanks @Klemen1337  and @dustinbolton

**Comment by Klemen1337** [comment]
@luckyagarwal3247 haha, sweet :smile:
