### ISSUE TITLE
How to print HTML formatted text

### ISSUE THREAD

**Issue by MY020537** [Klemen1337/node-thermal-printer#141]
Does this module support html template printing as well  anyhow ? i am able to print RAW text but not HTML formatted text.

**Comment by Klemen1337** [comment]
@MY020537 this library creates buffer with commands specifically for epson and star printers.

**Comment by WebScaffolder** [comment]
wha do you meant by create buffer, answer  yes or no or if possible then how?

**Comment by nipoonp** [comment]
I made it work like this using the node-html-to-image library.
```

        const image = await nodeHtmlToImage({
            html: `<html><body><div style="font-size: 24px;">Check out what I just did! #cool</div></body></html>`,
            quality: 20,
        });

        console.log("xxx... image", image);

        await printer.printImageBuffer(image); // Print PNG image

```

**Comment by fkoca** [comment]
Hi @nipoonp, your exemple didn't work for me. Nothing is printed. Do you have a special configuration?
