### ISSUE TITLE
Unable to connect printer via usb interface

### ISSUE THREAD

**Issue by yaxx** [Klemen1337/node-thermal-printer#143]
I'm trying connect the printer via usb. the printer port is set on USB001' so i set the interface to '\\.\USB001' instead of '\\.\COM1'. The printer could not connect and ended with these error
Error: EPERM: operation not permitted, open 'C:\.USB001'

I'm actually using win10 and Xprinter 58C

**Comment by zakaria-chahboun** [comment]
me too and i'm using LINUX

**Comment by Klemen1337** [comment]
Please use [node-printer](https://www.npmjs.com/package/printer) package to print on USB. Node printer will natively bind to printers on windows and linux operating systems.
