### ISSUE TITLE
Epson tm-t82 receipt ticket printer

### ISSUE THREAD

**Issue by Dannybrown2710** [Klemen1337/node-thermal-printer#145]
Hi Klemen, 
Thank you for making an amazing package. I have 2 questions
1. I have an Epson receipt printer, it is connected via USB port . How do I set the interface for it in the printer configuration?
2. Can i print a pdf file directly rather than writing a custom code for printing the bill?

**Comment by Klemen1337** [comment]
@Dannybrown2710 
1. I use this package with https://www.npmjs.com/package/printer to interface with the USB printer.

2. No, PDF and printer commands are two completely separate things. Some "graphical" printer drivers could do it but that has nothing to do with this package.
