### ISSUE TITLE
Is the library supported for TSC - TTP225 label printing model

### ISSUE THREAD

**Issue by rajjagani021** [Klemen1337/node-thermal-printer#150]
I want to know is this library supports the TSC model. This printer prints the KOT information of the sticker. Can this library do that thing as well? 
![31Ano0cMqTL](https://user-images.githubusercontent.com/4434991/87287484-ca77f400-c517-11ea-9848-5f1da8810d57.jpg)

**Comment by samuelcseto** [comment]
Hello! This library supports EPSON and STAR communication protocols. The printer you want to use uses TSPL-EZ protocol which unfortunately isn't compatible. Please refer to this document if you want to interact with this printer. 
[TSPL-EZ Programming Manual](https://www.meto.com/metoprint/files/meto_print_programming_manual_tspl_ez_en.pdf)

**Comment by Klemen1337** [comment]
@rajjagani021 label printers usually use different code and logic.
