### ISSUE TITLE
Not working for windows 

### ISSUE THREAD

**Issue by sidhdharth-navsoft** [Klemen1337/node-thermal-printer#169]
is this also work for windows ??
because I am getting this output  "ThermalPrinter-- Print done" for "log.info('ThermalPrinter--', execute);" but it's not printing anything and not opening cash drawer for windows pc.

I am trying to open the cash drawer without print but this is not working.

**Comment by afif-bouzid** [comment]
of course it works.
I advise you to configure your printer in share mode (ex: printer1)
and configure your file like this (
ex: let printer = new ThermalPrinter ({
        type: PrinterTypes.EPSON,
        interface: '// localhost/printer1',
      });
)

**Comment by JeanCarlosChavarriaHughes** [comment]
> of course it works. I advise you to configure your printer in share mode (ex: printer1) and configure your file like this ( ex: let printer = new ThermalPrinter ({ type: PrinterTypes.EPSON, interface: '// localhost/printer1', }); )


@afif-bouzid 's solution is working. 
Tested in Windows 11. 
Epson Printer (Hoin H58)
Node version 18.20.8
node-thermal-printer 4.6.0

Printer must be configured as Shared resource in Panel Control, and Interface should be `//localhost/printerName` 
cc @sidhdharth-navsoft
