### ISSUE TITLE
Implementation in React Js. fs module not found

### ISSUE THREAD

**Issue by theonardo23** [Klemen1337/node-thermal-printer#173]
I'm building a web app using React JS with typescript with Epson TM-U220D as the printer. I've done setting everything up, but when I try to run it, it always throws error related to fs. I've checked on my node-module/node and fs is there. Here's how I setup my printing page.

```
import React, { FunctionComponent } from 'react'
import { Button } from 'react-bootstrap'
import ThermalPrinter from 'node-thermal-printer'

export const PrintReceipt : FunctionComponent<> = () => {

    const printerNew = new ThermalPrinter.printer({
        type: ThermalPrinter.types.EPSON,
        interface: '/dev/usb/lp0'
    })

    const handlePrint = () =>{
        printItem()
    }

    const printItem = async() =>{
        const isConnected = await printerNew.isPrinterConnected()
        printerNew.println('Hello World')
        const result = await printerNew.execute()
        console.log(result)
    }

    return(
        <Button onClick={handlePrint}>Print Receipt</Button>
    )
}
```

For the code above it throws the error **fs.existsSync is not a function** . Is it anything to do with the project being build in typescript?

**Comment by Klemen1337** [comment]
This is NodeJS project. I also made a browser friendly version [https://github.com/Klemen1337/browser-thermal-printer](https://github.com/Klemen1337/browser-thermal-printer)
