### ISSUE TITLE
Printing Chinese to an EPSON TM T88V printer

### ISSUE THREAD

**Issue by jasnlink** [Klemen1337/node-thermal-printer#176]
I've tried setting charsets to CHINA from the examples.
I've tried encoding to CP936, ISO-8859-1, GBK, GB18030, BIG5 with iconv-lite and it's all printing in gibberish.
Is there a way to make this work?

**Comment by GuusToussaint** [comment]
Hi did you manage to fix this issue?

**Comment by jasnlink** [comment]
Yes, there is an international model of the TM T88V that comes with either simplified or traditional chinese fonts. I decided in the end to change brands and go with the STAR Micronics TSP143III. They come standard with asian character printing.
