### ISSUE TITLE
why node-thermal-printer not support arabic or unicode?

### ISSUE THREAD

**Issue by tishko18** [Klemen1337/node-thermal-printer#180]
i have issue when i wanna print invoice , my issue is not print unicode or arabic

how can i resolve this issue?

**Comment by haydave** [comment]
Also, Armenian letter are not supported.

**Comment by Alii-isk** [comment]
Any fix?

**Comment by pakxperts** [comment]
any fixes?

**Comment by Alii-isk** [comment]
> any fixes?
I found a workaround after alot of try and errors
U can dm me at fb to discuss more 
Fb.com/alii.isk

**Comment by pakxperts** [comment]
The fb link is broken..

**Comment by Alii-isk** [comment]
> The fb link is broken..

sorry i didn't realize that ,
i don't know the issue since the links works for me maybe its because i have my profile locked 

anyway ,you can leave me yours and i'll dm you.
