### ISSUE TITLE
beep() is not working

### ISSUE THREAD

**Issue by kdrmlhcn** [Klemen1337/node-thermal-printer#184]
Hello,

When using the [Escpos](https://www.npmjs.com/package/escpos) package, the beep function works as expected, but when I try to work with this package, the beep function does not work. Has anyone encountered this problem before?

**Comment by Klemen1337** [comment]
Please provide more information about your printer and implementation.

**Comment by Klemen1337** [comment]
https://github.com/Klemen1337/node-thermal-printer/commit/a65fbd6ff60a9ce21a6534e5939f1dc38f323199
