### ISSUE TITLE
driver

### ISSUE THREAD

**Issue by WebScaffolder** [Klemen1337/node-thermal-printer#186]

**Comment by jeremy-hoot** [comment]
Hey man I legit just got this error earlier. I found a work around for this. I needed to install this [package](https://www.npmjs.com/package/@thiagoelg/node-printer) and it was actually running. Then i was able to add the driver using this syntax.
`
let printMachine = new ThermalPrinter({
  type: PrinterTypes.STAR,
  interface: "printer:Star TSP143IIIBI Cutter",
  **driver: require("@thiagoelg/node-printer"),**
});`

and it worked for me. I hope this helps!

**Comment by Mayank-J0shi** [comment]
It does not work now.. I have tried it multiple times.
```
    const printer = new ThermalPrinter({
      type: PrinterTypes.STAR,
      interface: itfc,
      characterSet: CharacterSet.SLOVENIA,
      removeSpecialCharacters: false,
      lineCharacter: '=',
      breakLine: BreakLine.WORD,
      driver: require('@thiagoelg/node-printer')
    });
```
Gives out error : 
![image](https://user-images.githubusercontent.com/54811830/237056284-5220d57a-243c-4e80-9545-57eb26b38fe4.png)
