### ISSUE TITLE
there is a delay when we unplug the internet cable from router and do lan printing

### ISSUE THREAD

**Issue by sassymonks** [Klemen1337/node-thermal-printer#189]
we have unplugged the internet cable from the router and our printers are connected to the router in the local network. Our pc is connected to the router and doesn't have any internet if we try to print it offline it is taking 15 seconds delay to print but if we connect to the internet and print then there is no delay. is there any solution for this? can anyone help us out?

**Comment by Klemen1337** [comment]
this is strange. Please provide code example
