### ISSUE TITLE
bug with codeBar and QR ?

### ISSUE THREAD

**Issue by treeindark** [Klemen1337/node-thermal-printer#190]
printer.code128("Code128"); and printer.printQR("QR Code");  
Print nothing  !

printer.barCode("123456789");
print 123456789 !

Other Methods are ok!

I use last version (4.1.2), with Electron (17), print in electron-preload.js
Write with epson on windows share

**Comment by treeindark** [comment]
code128(data) not work, but with printer.barCode("123456789", 73)  it's ok.

**Comment by MehdiAlazhar** [comment]
Hi,
i encounter the same problem and i used several thermal printers and i cant find a function called barCode that you said resolve your problem i use the last version 4.1.2 as well.
can i have some assistance with this problem??
