### ISSUE TITLE
SP742ME GRY US

### ISSUE THREAD

**Issue by Tadija1986** [Klemen1337/node-thermal-printer#191]
Hello, I am using this library for printing from node server on Raspberry PI 4 to Star SP742 dot impact printer with Ethernet interface, and everything is working fine except printing image, QR code, barcode. When I try to print this things it is printing array of characters. What I am doing wrong? Emulation on printer is Star.

**Comment by thedigital** [comment]
Hi, i have the same issue with Epson type. Any news about this ?

**Comment by Klemen1337** [comment]
Please provide code examples
