### ISSUE TITLE
Epson function for CODE128 actually missing

### ISSUE THREAD

**Issue by hesa2020** [Klemen1337/node-thermal-printer#192]
Hello the function code128 is actually missing for Epson printers. here is how I implemented it for mine:

```
this.buffer = null;
this.append(this.config.BARCODE_CODE128);
this.append(Buffer.from([data.length + 2]));
this.append(Buffer.from([0x7b, 0x42]));
this.append(Buffer.from(data.toString()));
return this.buffer;
```

```
BARCODE_CODE128: Buffer.from([0x1d, 0x6b, 0x49])
```

It doesnt use any settings and has no text above/underneat and I am trying to figure how to implement those, however it seems to be working fine.

Edit:
I changed the function code to
```
this.buffer = null;
settings = settings || {};
// Set HRI characters Position, 0-3 (none, top, bottom, top/bottom)
if (settings.hriPos) {
	this.append(Buffer.from([0x1d, 0x48])); // GS H
	this.append(Buffer.from([settings.hriPos]));
} else {
	this.append(Buffer.from([0x1d, 0x48, 0x00]));
}
// Set HRI character font. 0-4, 48-52, 97, 98 (depending on printer, 0 and 1 available on all), default 0
if (settings.hriFont) {
	this.append(Buffer.from([0x1d, 0x66])); // GS f
	this.append(Buffer.from([settings.hriFont]));
} else {
	this.append(Buffer.from([0x1d, 0x66, 0x00]));
}
// Set width 2-6, default 3
if (settings.width) {
	this.append(Buffer.from([0x1d, 0x77])); // GS W
	this.append(Buffer.from([settings.width]));
} else {
	this.append(Buffer.from([0x1d, 0x77, 0x03]));
}
// Set height 1 - 255 default 162
if (settings.height) {
	this.append(Buffer.from([0x1d, 0x68])); // GS h
	this.append(Buffer.from([settings.height]));
} else {
	this.append(Buffer.from([0x1d, 0x68, 0xA2]));
}
// Print Barcode
this.append(this.config.BARCODE_CODE128);
this.append(Buffer.from([data.length + 2]));
this.append(Buffer.from([0x7b, 0x42]));
// Data
this.append(Buffer.from(data));
return this.buffer;
```
printer.code128('12345', {
  height: 80,
  hriPos: 2
});

**Comment by hesa2020** [comment]
Using printBarcode 73 didnt worked, it wrote the underneat text and took the space on paper but it wasnt printing any bars.

**Comment by treeindark** [comment]
hello, 
I'll use an epson compatible printer, but for code128 i need send :
·When using the CODE 128 in this printer, take the following points into
account for data transmission:
① The top of the bar code data string must be code set selection
character (any of CODE A, CODE B or CODE C) which selects the first code set.
② Special characters are defined by combining two characters
“{“ and one character. The ASCII character “{“ is defined by transmitting “{“ twice
consecutively.
Specific character Transmit data
                  ASCII Hex Decimal
SHIFT      |  {S   |  7B,53  |  123,83
CODE  A  |  {A  |  7B,41  |  123,65
CODE  B  |  {B  |   7B,42  |  123,66
CODE C   |  {C  |  7B,43  |  123,67

I don'know how todo that ... (actualy my code128 is a sadly  UPC_E)

**Comment by Klemen1337** [comment]
@hesa2020  Can you make a PR?

**Comment by racoononmoon** [comment]
you still can print Code128 AUTO using type 79 instead of 73 without any code adaptations
[https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=128]

`printer.printBarcode("SOME-CODE128-DATA", 79, {hriPos:4, hriFont:0, width: 2, height: 40}); `

also, same approach as above can be added to the printBarcode function in lib\types\epson.js
the encoding should ideally be a settings parameter
 
```
// Print Barcode
    this.append(Buffer.from([0x1d, 0x6b])); // GS k
    // Select type and bit length of data
    if(type && type == 73){
      this.append(Buffer.from([type, data.length + 2]));
      this.append(Buffer.from([0x7b, 0x41]));   //0x41 -CODE A, 0x42 -CODE B,  0x43 -CODE C, 
    } else{
      this.append(Buffer.from([type, data.length]));
    }
```

**Comment by TheWhiteShade** [comment]
> Using printBarcode 73 didnt worked, it wrote the underneat text and took the space on paper but it wasnt printing any bars.
> 
> until i changed:
> 
> ```
> this.append(Buffer.from([type, data.length]));
> ```
> 
> to:
> 
> ```
> if(type == 73)
> {
> 	this.append(Buffer.from([type, data.length + 2]));
> 	this.append(Buffer.from([0x7b, 0x42]));
> }
> else
> {
> 	this.append(Buffer.from([type, data.length]));
> }
> ```
> 
> Note: Tested and working with type 73 and 69.

This worked for me, thank you.
