### ISSUE TITLE
how to set paper size for 80mm print and 58 mm print 

### ISSUE THREAD

**Issue by sassymonks** [Klemen1337/node-thermal-printer#199]
We are unable to set print for 58mm paper size. how to set the paper sizes for 80mm print and 48 mm print? can anyone help us out?

**Comment by OverSamu** [comment]
Hi, you can try setting the number of characters per line via the width property of the configuration: 
https://github.com/Klemen1337/node-thermal-printer/blob/master/lib/core.js#L37 
By default it is 48 characters per line (i.e. paper width 80 mm).
