### ISSUE TITLE
network init

### ISSUE THREAD

**Issue by c3959** [Klemen1337/node-thermal-printer#2]
You can add as feature connect via network?
not only by printing through usb

**Comment by Klemen1337** [comment]
Hi @c3959,
we do not have network printers, so we didn't include that function. When we get our hands on the network printer we will support it.

This is a forked repository where they support net communication. 
https://github.com/Americas/node-thermal-printer/.

Cheers,
Klemen

**Comment by eatsleeplim** [comment]
is it possible have a function that returns (and one that clears) the printText? This would allow users (me!) to print using other means (like the npm printer module) without being tied down to using /dev/usb/lp0.

**Comment by Klemen1337** [comment]
@eatsleeplim I have added the clear and getText functions you have requested. We are still working on different kinds of communication and image printing. Currently we only have the USB printer, but we are trying to get the ethernet or serial thermal printers.

**Comment by Klemen1337** [comment]
@c3959 can you test the new version with network printing? I dont have a network printer :stuck_out_tongue_winking_eye:

**Comment by c3959** [comment]
this weekend will use a printer from the office for testing. I will discuss them how everything works. :D Cheers

**Comment by kikolobo** [comment]
Did it worked ?? Can you connect to several printers?

**Comment by Klemen1337** [comment]
Network printing is supported
