### ISSUE TITLE
STAR SM-L200 wont print EURO (€) symbol

### ISSUE THREAD

**Issue by fleksa-bhushan** [Klemen1337/node-thermal-printer#204]
We are getting started with the node-thermal printer and want to print German characters including EURO symbol, but  till now no luck already tried all character set incluing PC858_EURO  and https://github.com/Klemen1337/node-thermal-printer/issues/70 

Any one managed to get this working?

**Comment by geroale** [comment]
Same issue here

**Comment by zugende** [comment]
Same for me. Did you find a solution? @geroale @fleksa-bhushan
