### ISSUE TITLE
 openCashDrawer doesn't work for me

### ISSUE THREAD

**Issue by Wolyo** [Klemen1337/node-thermal-printer#210]
Finally after having some difficulties to be able to use this library, I was able to print a ticket using the example just add **printer.openCashDrawer();** but it does not open it, I use it in the click event of a button but the first time it does not open it but if I click more times it does open it and it opens it as many times as it does but if I put at least one **println** it prints the text as many times as I click the button and I only need to open it with a button and after printing, would you please help me?

excuse my english i used translator :P, but i can read it almost perfect

```
try {
  let execute = printer.execute()
  printer.openCashDrawer();
  console.error("Print done!");
} catch (error) {
  console.log("Print failed:", error);
}
```

**Comment by Klemen1337** [comment]
Hi 👋 You are executing the printer commands before open cash drawer is added to the commands buffer.

```javascript
const ThermalPrinter = require("node-thermal-printer").printer;
const PrinterTypes = require("node-thermal-printer").types;

// Init printer buffer
const printer = new ThermalPrinter({
  type: PrinterTypes.EPSON,
  interface: 'tcp://xxx.xxx.xxx.xxx'
});

// Add commands to the buffer
printer.openCashDrawer();

// Execute buffer with commands
try {
  printer.execute();
  console.error("Print done!");
} catch (error) {
  console.log("Print failed:", error);
}
```
