### ISSUE TITLE
EPSON TM88 MODEL PRINTER  RUN LINUX DEBIAN

### ISSUE THREAD

**Issue by arslan-mert** [Klemen1337/node-thermal-printer#217]
Hi guys

I have a linaro board and a tm88 model epson printer printer. I've checked your github file and I'm getting an error even though I'm using libraries and modules. Is there anything else I should do? I'm attaching the screenshot of the errors I got below. Thanks in advance for your help. The operating system I am using is linux debian 9.13.

thanks  

source code node.js

const { NodeThermalPrinter } = require("node-thermal-printer");

const printer =  new NodeThermalPrinter({
    type: "epson",
    interface: "serial",
    options: {
        port: "/dev/ttyS3",
        baudRate: 9600
    }
});

printer.init()
  .then(() => {
    printer.alignCenter();
    printer.print("Hello world\n");
    printer.cut();
    printer.execute(err => {
      if (err) {
        console.error("Print failed", err);
      } else {
        console.log("Print done");
      }
    });
  })
  .catch(err => {
    console.error("Printer initialization failed", err);
  });

-----------------------------------------------------------------------------------------------------------------------------------------
compile node.js output

const printer =  new NodeThermalPrinter({
                 ^

TypeError: NodeThermalPrinter is not a constructor
    at Object.<anonymous> (/var/www/kodxmcu/kodxmcu_sources/kodxmcu_mps_pr_01/mert.js:4:18)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.6.0

**Comment by Klemen1337** [comment]
```js
const { ThermalPrinter } = require('node-thermal-printer');

let printer = new ThermalPrinter({
```
