### ISSUE TITLE
Incompatible architecture (have 'x86_64', need 'arm64')

### ISSUE THREAD

**Issue by nipoonp** [Klemen1337/node-thermal-printer#221]
Does anyone know how to solve this issue?

<img width="503" alt="1" src="https://user-images.githubusercontent.com/16023800/233824234-92303605-7af6-48b4-81f3-60b1563bd96a.png">
<img width="1231" alt="2" src="https://user-images.githubusercontent.com/16023800/233824256-932e24bf-e2cf-430a-b0ef-74297745b1e0.png">

I am using Macbook Pro M2 Apple Silicon. How do I compile the printer binaries for arm64?

I am trying to run ```electron ./build/electron.js```

**Comment by Klemen1337** [comment]
This is related to the `node-printer` package.
