### ISSUE TITLE
Can't connect to usb printer EPSON TM-T20X

### ISSUE THREAD

**Issue by sousawalker** [Klemen1337/node-thermal-printer#224]
I have an EPSON TM-T20X printer, which is listed as one of the tested printers. And I can't send anything to it, if I send it directly through the browser, I can print it, but using your module or examples it doesn't show the connected printer. I'm using USB, on port TMUSB001.

**Comment by PedroBarbosaSw** [comment]
I'm havin the same issue. Did you find any solution for that?

**Comment by sousawalker** [comment]
I created a desktop application with C#, connecting in websocket and sending the bills to the printers.

**Comment by Klemen1337** [comment]
Please provide code examples when you open issues like this. This is a WebUSB issue or missconfiguration.
