### ISSUE TITLE
thought: print empty string instead of throwing error

### ISSUE THREAD

**Issue by seiyria** [Klemen1337/node-thermal-printer#23]
right now, if you try to println null, you get `cannot read property length of null`. for me, I'd rather it just print an empty string.

**Comment by Klemen1337** [comment]
So you just want to add new line or in case your object value is null?

**Comment by seiyria** [comment]
Basically, yeah. Otherwise you get an error when your value is null. I'd rather validate the physical receipt than it say "your string is null" and then have to guess what string it could possibly be.

**Comment by Klemen1337** [comment]
Fixed in 4.0.0-alpha
