### ISSUE TITLE
not able to connect thermal printer(80C)

### ISSUE THREAD

**Issue by praveen-tripathi** [Klemen1337/node-thermal-printer#24]
printer.isPrinterConnected( function(isConnected){ console.log(isConnected); } );
always returns false, while printer is connected.

**Comment by Klemen1337** [comment]
if you look at the isPrinterConnected function you can see it just checks if the interface exists. That probably works only for linux. If you are using windows please use it with [printer](https://www.npmjs.com/package/printer) library.
