### ISSUE TITLE
Error in NODEJS production

### ISSUE THREAD

**Issue by MasterProvider** [Klemen1337/node-thermal-printer#247]
Error in NODEJS production
`(node:3554) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

**Comment by adnanlah** [comment]
Hello, I don't know what are you planning to do but I think the error is self explanatory. You should use `Buffer.from(someValue)` instead of `Buffer(someValue)`.
