### ISSUE TITLE
Using this Module in Ember Js

### ISSUE THREAD

**Issue by papakay** [Klemen1337/node-thermal-printer#25]
Hello, please i have tried to import this module into an ember Js app using ember-browserify on a macOs laptop. The import but i got this issue when i tried to execute printer commands following the example provide on the README.

```index.js:53 Uncaught TypeError: fs.writeFile is not a function```

Please how can i resolve this?

Thank you.

**Comment by Klemen1337** [comment]
Sorry I can't help you with ember. I see no fs.writeFile in this module. What version of node are you using?
