### ISSUE TITLE
I get stocked in printer.execute(...)

### ISSUE THREAD

**Issue by ivanfelipecp** [Klemen1337/node-thermal-printer#26]
Hello, i get stocked in printer.execute()
this is my code

var printer = require("node-thermal-printer");

printer.init({
  type: 'epson',
  interface: '/dev/usb/lp0'
});

printer.println("Helloworld");
printer.execute(function(err){
    console.log("enters");
    if (err) {
      console.error("Print failed", err);
    } else {
     console.log("Print done");
    }
    printer.clear();
});

The program dont execute the line "console.log("enters");"

**Comment by KostadinP** [comment]
Try to run your script as admin. I had the same problem. Is there any way to avoid it?

**Comment by Klemen1337** [comment]
Well no because /dev/usb/lp0 is usually non writable for the normal user.
