### ISSUE TITLE
work in ios 10 ?

### ISSUE THREAD

**Issue by solinad21** [Klemen1337/node-thermal-printer#27]

**Comment by Klemen1337** [comment]
This is a nodeJS module

**Comment by solinad21** [comment]
Yes I know, but I want to know if with this module nodejs I can print on iOS 10 (laptop mac)?

**Comment by Klemen1337** [comment]
You mean OSX aka macOS?

**Comment by solinad21** [comment]
very sorry, yes i mean MAC OS X

**Comment by Klemen1337** [comment]
Place check issue https://github.com/Klemen1337/node-thermal-printer/issues/9.
