### ISSUE TITLE
Need help with border for table 

### ISSUE THREAD

**Issue by anujmv** [Klemen1337/node-thermal-printer#34]
Hi,  this works very well along with printer package for Windows, including QR and Barcode. 
Tested on Epson TM-T82.  However,  am not able to find any doc on how to draw border for table. 
Please help. 
Thank you.

**Comment by Klemen1337** [comment]
Well you have to draw border with characters.
Something like this:
+--------------------+
|                 |        |
|                 |        |
+--------------------+
