### ISSUE TITLE
support for Brother P-tocuh printers?

### ISSUE THREAD

**Issue by alandoyle95** [Klemen1337/node-thermal-printer#37]
could this feature get added? 

http://www.brother.com/product/dev/outline/index.htm

in more detail.. for this printer?
https://www.brother-usa.com/support/ModelInfo.aspx?R3ModelID=ptp700

and could we get it to load a pre existing template file?

would LOVE this feature to get added. and would be willing to pay to have it added. need this for a project im working on. would be willing to spend in 100's area for the feature.

**Comment by Klemen1337** [comment]
This is a different type of printer, sorry.
