### ISSUE TITLE
print via bluetooth

### ISSUE THREAD

**Issue by ngocminh237** [Klemen1337/node-thermal-printer#38]
hello, thank you for your project. do it support print via star bluetooth and zebra bluetooth?
thank you

**Comment by Klemen1337** [comment]
Zebra printers works totally different.

**Comment by buraky84** [comment]
i have the same question. i work with android and ios via react-native. i wonder if i could be able to connect to ESC POS Thermal printer via this library and print images etc.

**Comment by Klemen1337** [comment]
@buraky84 I don't know if you can use node packages with react native.
