### ISSUE TITLE
Can't connect to printer Epson TM-20ii

### ISSUE THREAD

**Issue by mipod** [Klemen1337/node-thermal-printer#43]
Hello,

I amtrying to connect to a Epson TM-20ii thermal printer through usbbut all i get is false when i run isPrinterConnected. Any solution that i could try to conenect to the printer? I have tryied changing the interfacein init but with no luck.

Thank you for your time

**Comment by Klemen1337** [comment]
Hi @mipod,
what operating system are you using?

**Comment by mipod** [comment]
Hello @Klemen1337 ,
I am currently runing on Windows 10 x64.

**Comment by Klemen1337** [comment]
If you wanna print through USB port, use it with [Printer](https://www.npmjs.com/package/printer) npm module.
