### ISSUE TITLE
How to print a html element?

### ISSUE THREAD

**Issue by Dineshrajaa** [Klemen1337/node-thermal-printer#5]
Hi all,
 How can I use this module to print a html element?kindly help me to do that
P.S:
I am using Angular JS as front end I need to print a particular div

**Comment by Klemen1337** [comment]
Hi @Dineshrajaa,
this module is used server side with Node.js. You would need to set up a Node.js server that would communicate with your frontend Angular app. Check out this stackoverflow question: http://goo.gl/T0NgKV, it might help you.
