### ISSUE TITLE
fs.writeFile is not a function

### ISSUE THREAD

**Issue by AnuSheeba** [Klemen1337/node-thermal-printer#51]
Hai,
 I used node thermal printer for access EPSON printer in my application.This npm is dependent on 

> fs npm

but when i execute printer, i got error like this fs.writeFile is not a function.

`printer.init({
  type: 'epson',
  interface: '\USB\VID_04B8&PID_0E15'
});
console.log("print",printer);
if(printer.isPrinterConnected){
  console.log('isPrinterConnected');
}
else{
  console.log('not Connected');
}
printer.cut();
try {
  printer.execute()
} catch (error) {
  console.log("Print failed", error);
}`

**Comment by Klemen1337** [comment]
@AnuSheeba hi, what version of node are you using? fs is part of node. If you are using a never version it might not work.
