### ISSUE TITLE
Is compatible with Epson TM-T20?

### ISSUE THREAD

**Issue by dbarjs** [Klemen1337/node-thermal-printer#52]
I'm buying an Epson TM-T20 printer. Has anyone tested on it yet?
Thanks

**Comment by gugadev** [comment]
@dbarjs At my job we use the model TM-T20II for our electronic billing systems without problems. Some times the printer does not print, so we need to reset the printer, but I don't know yet if this is problem of this package or something else.

**Comment by daniel-at-yoke** [comment]
I've been using this package with a TM-T20II from a Raspberry Pi (using CUPS and [this unofficial driver](https://github.com/plinth666/epsonsimplecups)), and it works like a charm. Haven't had any issues with it
