### ISSUE TITLE
How to generate multiple print copies and print same content to multiple printer

### ISSUE THREAD

**Issue by keerthi158** [Klemen1337/node-thermal-printer#62]
Hi,
I have used this package and it is working good. I have some requirement in printing as below.
1) How could I print multiple copies(2,3,4 etc) of **same content**?
2) Is there any way to send the **same content to multiple printers**?
Please guide me to sort out this issues.
Thanks.

**Comment by Klemen1337** [comment]
Hi, did you try the getBuffer()? Save buffer and print it multiple times
