### ISSUE TITLE
printer.isPrinterConnected() return "not connected" alert two times

### ISSUE THREAD

**Issue by keerthi158** [Klemen1337/node-thermal-printer#64]
I am printing over WiFi. 
If the printer is off, the callback is triggered two times. Here "printer is not connected! Please check it!." alert is showing two times.

Sometimes, Even In the printer ON condition, "printer is not connected! Please check it!." alert is showing after that printing has happening.(Print done alert).

Does it actual behavior or bug?

    `printer.isPrinterConnected(function(isConnected){
      console.log(isConnected);
      if(isConnected){
        printer.cut();
        printer.execute(function(err){
          if (err) {
            alert("Print failed", err);
          }else{
            alert("Print done");
          }
        });
      }else{
        alert("printer is not connected! Please check it!.");
      }
    });`

Thanks.

**Comment by Klemen1337** [comment]
@keerthi158 I'm sorry I cannot help you. I haven't tried it with the Wifi printer.

**Comment by kozmoz** [comment]
Experiencing the same issue with my network printer. It appears that the timeout is triggering even if the connection is already successful established. Will create a path to have this fixed.

**Comment by Klemen1337** [comment]
Fixed in 4.0.0-alpha
