### ISSUE TITLE
Print QRCode Buffer inside table.

### ISSUE THREAD

**Issue by VyankeshH** [Klemen1337/node-thermal-printer#67]
I am unable to get QRCode using table.

**Comment by Klemen1337** [comment]
@VyankeshH can you tell me more about what you are trying to do and post a code snippet.

**Comment by VyankeshH** [comment]
@Klemen1337 
var qrBuffer =  getQRCodeBufferData (qrCodeString , version, level, size);
where I got buffer data which I want to print on my bluetooth thermal printer.But I also want to table data should also with QRCode.So how can I print this.

**Comment by Klemen1337** [comment]
Currently it is not possible. Tables only work with text
