### ISSUE TITLE
Formatting Issues

### ISSUE THREAD

**Issue by 503Dev** [Klemen1337/node-thermal-printer#72]
Environment: Windows x64
Printer: POS58 (58mm Epson based thermal)
Line width: 48

When using the "left-right" and "table" print methods the farthest right item is always dropped to the next line even with short text, even when there is enough room.

Printing images with center align results in a left justification always.

Additionally, if I use the custom table as per below:
`            printer.tableCustom([                               // Prints table with custom settings (text, align, width, bold)
                { text:"Left", align:"LEFT", width:0.33 },
                { text:"Center", align:"CENTER", width:0.33, bold:true },
                { text:"Right", align:"RIGHT", width:0.33 }
              ]); `

This results in Left on the Left, Center to the right most position and right on the second line in the center.  This indicates a very likely issue with detecting **line width**.  Is there a way to tell the package the width? I know how to detect it but it seems it's not being observed in the program.

**Comment by kozmoz** [comment]
You can set the width for the printer during the init step, see the example below. 

Also to prevent rounding issues, it's better to write **1/3**, instead of **0.33** for the cell width.

But even then sometimes the total width is a character off. I think the `tableCustom()` function needs some improvements in that area.

```javascript
printer.init({
            type: printer.printerTypes.EPSON,
            interface: 'tcp://10.0.1.23:9100',
            width: 48
        });
```
