### ISSUE TITLE
how to print in windows? Printer isConnected true but not print.

### ISSUE THREAD

**Issue by pporcel** [Klemen1337/node-thermal-printer#77]
The connection returns true but the printer does not print. I share the code used. I am work in Electron with Windows 8.
I apologize if I have a typing error, I am using an online translator.

Thanks!

var printer = require("node-thermal-printer");
printer.init({
  type: 'epson',
  interface: 'ESDPRT001',
  printer: 'auto'
});

printer.alignCenter();
printer.println("Hello world");
printer.printQR("https://github.com/Klemen1337/node-thermal-printer"); // Print QR code
printer.cut();
printer.execute(function(err){
   if (err) {
     console.error("Print failed", err);
   } else {
    console.log("Print done");
   }
});

**Comment by Cesarlachapelle** [comment]
Same here, I cant print on windows, and I have the same code, i have the TM-T20II

**Comment by KhanMaytok** [comment]
Hi. I can print in windows. I installed "printer" module for detect the printer . This is the code:

```
const m_printer = require('printer')
const default_printer = m_printer.getDefaultPrinterName();
```


Then, in the config: 

```
printer.init({
    type: 'epson',                                     
    interface: `printer:${default_printer}`, 
...
```

I have the TM-T20II too
