### ISSUE TITLE
Init Interface

### ISSUE THREAD

**Issue by TheJotne** [Klemen1337/node-thermal-printer#79]
Hello
I try to get the module to work since a few days.
I use interface: 'printer:Thermalprinter', to init the printer but it doesn't work. I work on ubuntu and could not find a dev/usb/lp path so i tried the printer module.
Can someone show me a complete js file where the init trough printer worked?
many thanks

**Comment by SloInfinity** [comment]
Please see examples https://github.com/Klemen1337/node-thermal-printer/tree/master/examples
