### ISSUE TITLE
Special Characters not displaying properly

### ISSUE THREAD

**Issue by ChazUK** [Klemen1337/node-thermal-printer#8]
I've had to manually add 

`specialCharacters: {
     "£": 35,
    "@": 64
}`

to epsonConfig to enable these special characters. Can there not be a way to extend and support our own character set?

**Comment by Klemen1337** [comment]
@ChazUK I will try to add support as soon as I can.

**Comment by sadlyblue** [comment]
I don't really know how to work with git and github, but i've made a fork to include support for Windows 1252 charset to the epson. If you are interested, just add to the main development.

**Comment by ntyrrell** [comment]
Hi @sadlyblue, could you upload your fix as a code block for forking the repository?

**Comment by sadlyblue** [comment]
Hi @ntyrrell, sorry for the late reply. I'm not very familiar how to use github. But i've added the code to a new fork. I think you can find it in my account. Basically I added the charSet WPC1252, and the corresponding special characters.

**Comment by ntyrrell** [comment]
Hi @sadlyblue, no worries! I managed to spot that, thank you for sharing 😄 In the end, I ended up doing my own fork as I am using a Star printer, but my hope is that it allows for specifying custom special characters (see #32)
