### ISSUE TITLE
Can I use this to print on a Web browser independent operating system?

### ISSUE THREAD

**Issue by vinhtien** [Klemen1337/node-thermal-printer#87]
Hello,

I found your interesting source code for printing with Epson thermal printer.

However, I just have a small question that if I intend to use a HTML loaded on a Web browser and this trigger the print through your javascript codes, is it possible? Because it will not possible for me to install dependencies on the device loading this HTML. But include the lib through <script> is indeed ok.

**Comment by Klemen1337** [comment]
This is a [NodeJS](https://nodejs.org/en/about/) module.
